# Generated by Django 6.0.2 on 2026-02-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_vote_created_at_poll_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
