# Generated by Django 6.0.2 on 2026-02-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_vote_ip_address_vote_device_id_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
