# Generated by Django 6.0.2 on 2026-02-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_poll_expires_at_remove_vote_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
